name: Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install --all-extras  # also tests asymmetric with cryptography

      - name: Lint
        run: poetry run ruff format && poetry run ruff check

      - name: Test
        working-directory: ./tests
        run: poetry run pytest

      - name: Test pydantic v1 compatibility
        working-directory: ./tests
        run: poetry run pip install 'pydantic<2' && poetry run pytest
      - run: poetry build
